### IMPORT THE FILES PATH ###
### CLEAN THE DATA

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [3]:
acct = pd.read_csv(r"C:\Users\Ifeoluwa\OneDrive\Documents\Finlora\data\raw\finlora_accounts.csv")
txn = pd.read_csv(r"C:\Users\Ifeoluwa\OneDrive\Documents\Finlora\data\raw\finlora_transactions.csv")

In [4]:
acct.head()

,account_id,account_holder_name,account_type,home_country,currency,kyc_tier,account_created_date,personal_spend_baseline_usd
0,FLR-ACC-100000,Amaka Okafor,Individual,NG,NGN,Tier3_Enhanced,2022-08-28,63.23
1,FLR-ACC-100001,Bluewave Foods Ltd,Business,NG,NGN,Tier1_Basic,2026-04-27,810.68
2,FLR-ACC-100002,Global Trading LLC,Business,US,USD,Tier2_Verified,2026-03-29,433.67
3,FLR-ACC-100003,Femi Adeyemi,Individual,NG,NGN,Tier3_Enhanced,2025-09-15,19.18
4,FLR-ACC-100004,Ngozi Brown,Individual,NG,NGN,Tier3_Enhanced,2024-06-18,28.68

In [5]:
acct.info()

<class 'pandas.DataFrame'>
RangeIndex: 7200 entries, 0 to 7199
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   account_id                   7200 non-null   str
 1   account_holder_name          7200 non-null   str
 2   account_type                 7200 non-null   str
 3   home_country                 7200 non-null   str
 4   currency                     7200 non-null   str
 5   kyc_tier                     7200 non-null   str
 6   account_created_date         7200 non-null   str
 7   personal_spend_baseline_usd  7200 non-null   float64
dtypes: float64(1), str(7)
memory usage: 450.1 KB

In [6]:
acct.isnull().sum()

account_id                     0
account_holder_name            0
account_type                   0
home_country                   0
currency                       0
kyc_tier                       0
account_created_date           0
personal_spend_baseline_usd    0
dtype: int64

In [7]:
acct.duplicated().sum()

np.int64(0)

In [9]:
for col in ['account_holder_name', 'personal_spend_baseline_usd', 'account_type']:
    print(col, acct[col].unique())
    print()

account_holder_name <StringArray>
[            'Amaka Okafor',       'Bluewave Foods Ltd',
       'Global Trading LLC',             'Femi Adeyemi',
              'Ngozi Brown',  'Global Technologies Co.',
                'Olu Bello',          'North Foods Co.',
  'Greenfield Textiles Ltd',            'David Johnson',
 ...
      'Global Builders LLC',       'Prime Builders Co.',
      'Prime Logistics Co.',                'Ben Smith',
 'Greenfield Logistics Co.',     'Greenfield Media LLC',
       'Prime Textiles Inc',      'Global Textiles Ltd',
             'Musa Ibrahim',       'Prime Textiles Ltd']
Length: 1000, dtype: str

personal_spend_baseline_usd [  63.23  810.68  433.67 ... 1617.25   28.02  153.79]

account_type <StringArray>
['Individual', 'Business']
Length: 2, dtype: str

In [10]:
txn.head()

,transaction_id,account_id,account_type,kyc_tier,timestamp,day_of_week,hour_of_day,description,merchant_name,merchant_category,...,avg_transaction_amount_30d,transaction_velocity_1h,transaction_country,home_country,is_cross_border,device_id,is_new_device,account_age_days,status,is_fraud
0,FLR250216186265,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-02-16 14:55:35,Sunday,14,CNP PURCHASE - BOLT,Bolt,Travel,...,9143.33,0,NG,NG,0,NaN,NaN,903,Completed,0
1,FLR250423143305,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-23 13:35:40,Wednesday,13,WEB PURCHASE - SLACK,Slack,Subscription/SaaS,...,9143.33,0,NG,NG,0,NaN,NaN,969,Declined,0
2,FLR250424154897,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-24 12:30:34,Thursday,12,MOBILE PURCHASE - JUSTRITE SUPERSTORE,Justrite Superstore,Groceries,...,9143.33,0,NG,NG,0,DEV-9055235108,0.0,970,Completed,0
3,FLR250428101772,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-28 14:41:59,Monday,14,CNP PURCHASE - ADOBE CREATIVE CLOUD,Adobe Creative Cloud,Subscription/SaaS,...,14891.16,0,NG,NG,0,NaN,NaN,974,Completed,0
4,FLR250628102827,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-06-28 16:15:47,Saturday,16,MOBILE PURCHASE - APPLE STORE,Apple Store,Electronics,...,49609.59,0,NG,NG,0,DEV-9055235108,0.0,1035,Declined,0

In [11]:
txn.info()

<class 'pandas.DataFrame'>
RangeIndex: 126000 entries, 0 to 125999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   transaction_id              126000 non-null  str
 1   account_id                  126000 non-null  str
 2   account_type                126000 non-null  str
 3   kyc_tier                    126000 non-null  str
 4   timestamp                   126000 non-null  str
 5   day_of_week                 126000 non-null  str
 6   hour_of_day                 126000 non-null  int64
 7   description                 126000 non-null  str
 8   merchant_name               97390 non-null   str
 9   merchant_category           126000 non-null  str
 10  channel                     126000 non-null  str
 11  amount                      126000 non-null  float64
 12  currency                    126000 non-null  str
 13  amount_to_avg_ratio         126000 non-null  float64
 14  avg_transaction_amount_30d  126000 non-null  float64
 15  transaction_velocity_1h     126000 non-null  int64
 16  transaction_country         126000 non-null  str
 17  home_country                126000 non-null  str
 18  is_cross_border             126000 non-null  int64
 19  device_id                   111666 non-null  str
 20  is_new_device               111666 non-null  float64
 21  account_age_days            126000 non-null  int64
 22  status                      126000 non-null  str
 23  is_fraud                    126000 non-null  int64
dtypes: float64(4), int64(5), str(15)
memory usage: 23.1 MB

In [12]:
txn.isnull().sum()

transaction_id                    0
account_id                        0
account_type                      0
kyc_tier                          0
timestamp                         0
day_of_week                       0
hour_of_day                       0
description                       0
merchant_name                 28610
merchant_category                 0
channel                           0
amount                            0
currency                          0
amount_to_avg_ratio               0
avg_transaction_amount_30d        0
transaction_velocity_1h           0
transaction_country               0
home_country                      0
is_cross_border                   0
device_id                     14334
is_new_device                 14334
account_age_days                  0
status                            0
is_fraud                          0
dtype: int64

In [14]:
txn.duplicated().sum()

np.int64(0)

In [15]:
txn['merchant_name'].value_counts().head(10)

merchant_name
International Wire    7584
Jumia                 2365
Apple Store Online    2311
Zara                  2279
ASOS                  2264
Amazon                2233
Konga                 2192
British Gas           2135
EEDC                  2112
Thames Water          2059
Name: count, dtype: int64

In [16]:
txn['merchant_name'] = txn['merchant_name'].fillna('Unknown')

In [17]:
txn.info()

<class 'pandas.DataFrame'>
RangeIndex: 126000 entries, 0 to 125999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   transaction_id              126000 non-null  str
 1   account_id                  126000 non-null  str
 2   account_type                126000 non-null  str
 3   kyc_tier                    126000 non-null  str
 4   timestamp                   126000 non-null  str
 5   day_of_week                 126000 non-null  str
 6   hour_of_day                 126000 non-null  int64
 7   description                 126000 non-null  str
 8   merchant_name               126000 non-null  str
 9   merchant_category           126000 non-null  str
 10  channel                     126000 non-null  str
 11  amount                      126000 non-null  float64
 12  currency                    126000 non-null  str
 13  amount_to_avg_ratio         126000 non-null  float64
 14  avg_transaction_amount_30d  126000 non-null  float64
 15  transaction_velocity_1h     126000 non-null  int64
 16  transaction_country         126000 non-null  str
 17  home_country                126000 non-null  str
 18  is_cross_border             126000 non-null  int64
 19  device_id                   111666 non-null  str
 20  is_new_device               111666 non-null  float64
 21  account_age_days            126000 non-null  int64
 22  status                      126000 non-null  str
 23  is_fraud                    126000 non-null  int64
dtypes: float64(4), int64(5), str(15)
memory usage: 23.1 MB

In [18]:
txn['device_id'] = txn['device_id'].fillna('Unknown_id')

In [19]:
txn.info()

<class 'pandas.DataFrame'>
RangeIndex: 126000 entries, 0 to 125999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   transaction_id              126000 non-null  str
 1   account_id                  126000 non-null  str
 2   account_type                126000 non-null  str
 3   kyc_tier                    126000 non-null  str
 4   timestamp                   126000 non-null  str
 5   day_of_week                 126000 non-null  str
 6   hour_of_day                 126000 non-null  int64
 7   description                 126000 non-null  str
 8   merchant_name               126000 non-null  str
 9   merchant_category           126000 non-null  str
 10  channel                     126000 non-null  str
 11  amount                      126000 non-null  float64
 12  currency                    126000 non-null  str
 13  amount_to_avg_ratio         126000 non-null  float64
 14  avg_transaction_amount_30d  126000 non-null  float64
 15  transaction_velocity_1h     126000 non-null  int64
 16  transaction_country         126000 non-null  str
 17  home_country                126000 non-null  str
 18  is_cross_border             126000 non-null  int64
 19  device_id                   126000 non-null  str
 20  is_new_device               111666 non-null  float64
 21  account_age_days            126000 non-null  int64
 22  status                      126000 non-null  str
 23  is_fraud                    126000 non-null  int64
dtypes: float64(4), int64(5), str(15)
memory usage: 23.1 MB

In [20]:
txn.head()

,transaction_id,account_id,account_type,kyc_tier,timestamp,day_of_week,hour_of_day,description,merchant_name,merchant_category,...,avg_transaction_amount_30d,transaction_velocity_1h,transaction_country,home_country,is_cross_border,device_id,is_new_device,account_age_days,status,is_fraud
0,FLR250216186265,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-02-16 14:55:35,Sunday,14,CNP PURCHASE - BOLT,Bolt,Travel,...,9143.33,0,NG,NG,0,Unknown_id,NaN,903,Completed,0
1,FLR250423143305,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-23 13:35:40,Wednesday,13,WEB PURCHASE - SLACK,Slack,Subscription/SaaS,...,9143.33,0,NG,NG,0,Unknown_id,NaN,969,Declined,0
2,FLR250424154897,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-24 12:30:34,Thursday,12,MOBILE PURCHASE - JUSTRITE SUPERSTORE,Justrite Superstore,Groceries,...,9143.33,0,NG,NG,0,DEV-9055235108,0.0,970,Completed,0
3,FLR250428101772,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-28 14:41:59,Monday,14,CNP PURCHASE - ADOBE CREATIVE CLOUD,Adobe Creative Cloud,Subscription/SaaS,...,14891.16,0,NG,NG,0,Unknown_id,NaN,974,Completed,0
4,FLR250628102827,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-06-28 16:15:47,Saturday,16,MOBILE PURCHASE - APPLE STORE,Apple Store,Electronics,...,49609.59,0,NG,NG,0,DEV-9055235108,0.0,1035,Declined,0

In [21]:
txn['timestamp'] = pd.to_datetime(txn['timestamp'], format='%Y-%m-%d %H:%M:%S')

In [22]:
txn.info()

<class 'pandas.DataFrame'>
RangeIndex: 126000 entries, 0 to 125999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   transaction_id              126000 non-null  str
 1   account_id                  126000 non-null  str
 2   account_type                126000 non-null  str
 3   kyc_tier                    126000 non-null  str
 4   timestamp                   126000 non-null  datetime64[us]
 5   day_of_week                 126000 non-null  str
 6   hour_of_day                 126000 non-null  int64
 7   description                 126000 non-null  str
 8   merchant_name               126000 non-null  str
 9   merchant_category           126000 non-null  str
 10  channel                     126000 non-null  str
 11  amount                      126000 non-null  float64
 12  currency                    126000 non-null  str
 13  amount_to_avg_ratio         126000 non-null  float64
 14  avg_transaction_amount_30d  126000 non-null  float64
 15  transaction_velocity_1h     126000 non-null  int64
 16  transaction_country         126000 non-null  str
 17  home_country                126000 non-null  str
 18  is_cross_border             126000 non-null  int64
 19  device_id                   126000 non-null  str
 20  is_new_device               111666 non-null  float64
 21  account_age_days            126000 non-null  int64
 22  status                      126000 non-null  str
 23  is_fraud                    126000 non-null  int64
dtypes: datetime64[us](1), float64(4), int64(5), str(14)
memory usage: 23.1 MB

In [23]:
txn.duplicated().sum()

np.int64(0)

In [24]:
txn.info()

<class 'pandas.DataFrame'>
RangeIndex: 126000 entries, 0 to 125999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   transaction_id              126000 non-null  str
 1   account_id                  126000 non-null  str
 2   account_type                126000 non-null  str
 3   kyc_tier                    126000 non-null  str
 4   timestamp                   126000 non-null  datetime64[us]
 5   day_of_week                 126000 non-null  str
 6   hour_of_day                 126000 non-null  int64
 7   description                 126000 non-null  str
 8   merchant_name               126000 non-null  str
 9   merchant_category           126000 non-null  str
 10  channel                     126000 non-null  str
 11  amount                      126000 non-null  float64
 12  currency                    126000 non-null  str
 13  amount_to_avg_ratio         126000 non-null  float64
 14  avg_transaction_amount_30d  126000 non-null  float64
 15  transaction_velocity_1h     126000 non-null  int64
 16  transaction_country         126000 non-null  str
 17  home_country                126000 non-null  str
 18  is_cross_border             126000 non-null  int64
 19  device_id                   126000 non-null  str
 20  is_new_device               111666 non-null  float64
 21  account_age_days            126000 non-null  int64
 22  status                      126000 non-null  str
 23  is_fraud                    126000 non-null  int64
dtypes: datetime64[us](1), float64(4), int64(5), str(14)
memory usage: 23.1 MB

In [25]:
txn.isnull().sum()

transaction_id                    0
account_id                        0
account_type                      0
kyc_tier                          0
timestamp                         0
day_of_week                       0
hour_of_day                       0
description                       0
merchant_name                     0
merchant_category                 0
channel                           0
amount                            0
currency                          0
amount_to_avg_ratio               0
avg_transaction_amount_30d        0
transaction_velocity_1h           0
transaction_country               0
home_country                      0
is_cross_border                   0
device_id                         0
is_new_device                 14334
account_age_days                  0
status                            0
is_fraud                          0
dtype: int64

In [27]:
txn.is_new_device.value_counts()

is_new_device
0.0    107771
1.0      3895
Name: count, dtype: int64

In [28]:
print(txn.columns.tolist())

['transaction_id', 'account_id', 'account_type', 'kyc_tier', 'timestamp', 'day_of_week', 'hour_of_day', 'description', 'merchant_name', 'merchant_category', 'channel', 'amount', 'currency', 'amount_to_avg_ratio', 'avg_transaction_amount_30d', 'transaction_velocity_1h', 'transaction_country', 'home_country', 'is_cross_border', 'device_id', 'is_new_device', 'account_age_days', 'status', 'is_fraud']