### IMPORT THE FILES PATH ###
### CLEAN THE DATA

In [30]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [31]:
acct = pd.read_csv(r"C:\Users\Ifeoluwa\OneDrive\Documents\Finlora\data\raw\finlora_accounts.csv")
txn = pd.read_csv(r"C:\Users\Ifeoluwa\OneDrive\Documents\Finlora\data\raw\finlora_transactions.csv")

In [32]:
acct.head()

,account_id,account_holder_name,account_type,home_country,currency,kyc_tier,account_created_date,personal_spend_baseline_usd
0,FLR-ACC-100000,Amaka Okafor,Individual,NG,NGN,Tier3_Enhanced,2022-08-28,63.23
1,FLR-ACC-100001,Bluewave Foods Ltd,Business,NG,NGN,Tier1_Basic,2026-04-27,810.68
2,FLR-ACC-100002,Global Trading LLC,Business,US,USD,Tier2_Verified,2026-03-29,433.67
3,FLR-ACC-100003,Femi Adeyemi,Individual,NG,NGN,Tier3_Enhanced,2025-09-15,19.18
4,FLR-ACC-100004,Ngozi Brown,Individual,NG,NGN,Tier3_Enhanced,2024-06-18,28.68

In [33]:
acct.info()

<class 'pandas.DataFrame'>
RangeIndex: 7200 entries, 0 to 7199
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   account_id                   7200 non-null   str
 1   account_holder_name          7200 non-null   str
 2   account_type                 7200 non-null   str
 3   home_country                 7200 non-null   str
 4   currency                     7200 non-null   str
 5   kyc_tier                     7200 non-null   str
 6   account_created_date         7200 non-null   str
 7   personal_spend_baseline_usd  7200 non-null   float64
dtypes: float64(1), str(7)
memory usage: 450.1 KB

In [34]:
acct.isnull().sum()

account_id                     0
account_holder_name            0
account_type                   0
home_country                   0
currency                       0
kyc_tier                       0
account_created_date           0
personal_spend_baseline_usd    0
dtype: int64

In [35]:
acct.duplicated().sum()

np.int64(0)

In [36]:
for col in ['account_holder_name', 'personal_spend_baseline_usd', 'account_type']:
    print(col, acct[col].unique())
    print()

account_holder_name <StringArray>
[            'Amaka Okafor',       'Bluewave Foods Ltd',
       'Global Trading LLC',             'Femi Adeyemi',
              'Ngozi Brown',  'Global Technologies Co.',
                'Olu Bello',          'North Foods Co.',
  'Greenfield Textiles Ltd',            'David Johnson',
 ...
      'Global Builders LLC',       'Prime Builders Co.',
      'Prime Logistics Co.',                'Ben Smith',
 'Greenfield Logistics Co.',     'Greenfield Media LLC',
       'Prime Textiles Inc',      'Global Textiles Ltd',
             'Musa Ibrahim',       'Prime Textiles Ltd']
Length: 1000, dtype: str

personal_spend_baseline_usd [  63.23  810.68  433.67 ... 1617.25   28.02  153.79]

account_type <StringArray>
['Individual', 'Business']
Length: 2, dtype: str

In [37]:
txn.head()

,transaction_id,account_id,account_type,kyc_tier,timestamp,day_of_week,hour_of_day,description,merchant_name,merchant_category,...,avg_transaction_amount_30d,transaction_velocity_1h,transaction_country,home_country,is_cross_border,device_id,is_new_device,account_age_days,status,is_fraud
0,FLR250216186265,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-02-16 14:55:35,Sunday,14,CNP PURCHASE - BOLT,Bolt,Travel,...,9143.33,0,NG,NG,0,NaN,NaN,903,Completed,0
1,FLR250423143305,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-23 13:35:40,Wednesday,13,WEB PURCHASE - SLACK,Slack,Subscription/SaaS,...,9143.33,0,NG,NG,0,NaN,NaN,969,Declined,0
2,FLR250424154897,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-24 12:30:34,Thursday,12,MOBILE PURCHASE - JUSTRITE SUPERSTORE,Justrite Superstore,Groceries,...,9143.33,0,NG,NG,0,DEV-9055235108,0.0,970,Completed,0
3,FLR250428101772,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-28 14:41:59,Monday,14,CNP PURCHASE - ADOBE CREATIVE CLOUD,Adobe Creative Cloud,Subscription/SaaS,...,14891.16,0,NG,NG,0,NaN,NaN,974,Completed,0
4,FLR250628102827,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-06-28 16:15:47,Saturday,16,MOBILE PURCHASE - APPLE STORE,Apple Store,Electronics,...,49609.59,0,NG,NG,0,DEV-9055235108,0.0,1035,Declined,0

In [38]:
txn.info()

<class 'pandas.DataFrame'>
RangeIndex: 126000 entries, 0 to 125999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   transaction_id              126000 non-null  str
 1   account_id                  126000 non-null  str
 2   account_type                126000 non-null  str
 3   kyc_tier                    126000 non-null  str
 4   timestamp                   126000 non-null  str
 5   day_of_week                 126000 non-null  str
 6   hour_of_day                 126000 non-null  int64
 7   description                 126000 non-null  str
 8   merchant_name               97390 non-null   str
 9   merchant_category           126000 non-null  str
 10  channel                     126000 non-null  str
 11  amount                      126000 non-null  float64
 12  currency                    126000 non-null  str
 13  amount_to_avg_ratio         126000 non-null  float64
 14  avg_transaction_amount_30d  126000 non-null  float64
 15  transaction_velocity_1h     126000 non-null  int64
 16  transaction_country         126000 non-null  str
 17  home_country                126000 non-null  str
 18  is_cross_border             126000 non-null  int64
 19  device_id                   111666 non-null  str
 20  is_new_device               111666 non-null  float64
 21  account_age_days            126000 non-null  int64
 22  status                      126000 non-null  str
 23  is_fraud                    126000 non-null  int64
dtypes: float64(4), int64(5), str(15)
memory usage: 23.1 MB

In [39]:
txn.isnull().sum()

transaction_id                    0
account_id                        0
account_type                      0
kyc_tier                          0
timestamp                         0
day_of_week                       0
hour_of_day                       0
description                       0
merchant_name                 28610
merchant_category                 0
channel                           0
amount                            0
currency                          0
amount_to_avg_ratio               0
avg_transaction_amount_30d        0
transaction_velocity_1h           0
transaction_country               0
home_country                      0
is_cross_border                   0
device_id                     14334
is_new_device                 14334
account_age_days                  0
status                            0
is_fraud                          0
dtype: int64

In [40]:
txn.duplicated().sum()

np.int64(0)

In [41]:
txn['merchant_name'].value_counts().head(10)

merchant_name
International Wire    7584
Jumia                 2365
Apple Store Online    2311
Zara                  2279
ASOS                  2264
Amazon                2233
Konga                 2192
British Gas           2135
EEDC                  2112
Thames Water          2059
Name: count, dtype: int64

In [42]:
txn.info()

<class 'pandas.DataFrame'>
RangeIndex: 126000 entries, 0 to 125999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   transaction_id              126000 non-null  str
 1   account_id                  126000 non-null  str
 2   account_type                126000 non-null  str
 3   kyc_tier                    126000 non-null  str
 4   timestamp                   126000 non-null  str
 5   day_of_week                 126000 non-null  str
 6   hour_of_day                 126000 non-null  int64
 7   description                 126000 non-null  str
 8   merchant_name               97390 non-null   str
 9   merchant_category           126000 non-null  str
 10  channel                     126000 non-null  str
 11  amount                      126000 non-null  float64
 12  currency                    126000 non-null  str
 13  amount_to_avg_ratio         126000 non-null  float64
 14  avg_transaction_amount_30d  126000 non-null  float64
 15  transaction_velocity_1h     126000 non-null  int64
 16  transaction_country         126000 non-null  str
 17  home_country                126000 non-null  str
 18  is_cross_border             126000 non-null  int64
 19  device_id                   111666 non-null  str
 20  is_new_device               111666 non-null  float64
 21  account_age_days            126000 non-null  int64
 22  status                      126000 non-null  str
 23  is_fraud                    126000 non-null  int64
dtypes: float64(4), int64(5), str(15)
memory usage: 23.1 MB

In [43]:
txn['device_id'] = txn['device_id'].fillna('Unknown_id')

In [44]:
txn.info()

<class 'pandas.DataFrame'>
RangeIndex: 126000 entries, 0 to 125999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   transaction_id              126000 non-null  str
 1   account_id                  126000 non-null  str
 2   account_type                126000 non-null  str
 3   kyc_tier                    126000 non-null  str
 4   timestamp                   126000 non-null  str
 5   day_of_week                 126000 non-null  str
 6   hour_of_day                 126000 non-null  int64
 7   description                 126000 non-null  str
 8   merchant_name               97390 non-null   str
 9   merchant_category           126000 non-null  str
 10  channel                     126000 non-null  str
 11  amount                      126000 non-null  float64
 12  currency                    126000 non-null  str
 13  amount_to_avg_ratio         126000 non-null  float64
 14  avg_transaction_amount_30d  126000 non-null  float64
 15  transaction_velocity_1h     126000 non-null  int64
 16  transaction_country         126000 non-null  str
 17  home_country                126000 non-null  str
 18  is_cross_border             126000 non-null  int64
 19  device_id                   126000 non-null  str
 20  is_new_device               111666 non-null  float64
 21  account_age_days            126000 non-null  int64
 22  status                      126000 non-null  str
 23  is_fraud                    126000 non-null  int64
dtypes: float64(4), int64(5), str(15)
memory usage: 23.1 MB

In [45]:
txn.head()

,transaction_id,account_id,account_type,kyc_tier,timestamp,day_of_week,hour_of_day,description,merchant_name,merchant_category,...,avg_transaction_amount_30d,transaction_velocity_1h,transaction_country,home_country,is_cross_border,device_id,is_new_device,account_age_days,status,is_fraud
0,FLR250216186265,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-02-16 14:55:35,Sunday,14,CNP PURCHASE - BOLT,Bolt,Travel,...,9143.33,0,NG,NG,0,Unknown_id,NaN,903,Completed,0
1,FLR250423143305,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-23 13:35:40,Wednesday,13,WEB PURCHASE - SLACK,Slack,Subscription/SaaS,...,9143.33,0,NG,NG,0,Unknown_id,NaN,969,Declined,0
2,FLR250424154897,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-24 12:30:34,Thursday,12,MOBILE PURCHASE - JUSTRITE SUPERSTORE,Justrite Superstore,Groceries,...,9143.33,0,NG,NG,0,DEV-9055235108,0.0,970,Completed,0
3,FLR250428101772,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-28 14:41:59,Monday,14,CNP PURCHASE - ADOBE CREATIVE CLOUD,Adobe Creative Cloud,Subscription/SaaS,...,14891.16,0,NG,NG,0,Unknown_id,NaN,974,Completed,0
4,FLR250628102827,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-06-28 16:15:47,Saturday,16,MOBILE PURCHASE - APPLE STORE,Apple Store,Electronics,...,49609.59,0,NG,NG,0,DEV-9055235108,0.0,1035,Declined,0

In [46]:
txn['timestamp'] = pd.to_datetime(txn['timestamp'], format='%Y-%m-%d %H:%M:%S')

In [47]:
txn.info()

<class 'pandas.DataFrame'>
RangeIndex: 126000 entries, 0 to 125999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   transaction_id              126000 non-null  str
 1   account_id                  126000 non-null  str
 2   account_type                126000 non-null  str
 3   kyc_tier                    126000 non-null  str
 4   timestamp                   126000 non-null  datetime64[us]
 5   day_of_week                 126000 non-null  str
 6   hour_of_day                 126000 non-null  int64
 7   description                 126000 non-null  str
 8   merchant_name               97390 non-null   str
 9   merchant_category           126000 non-null  str
 10  channel                     126000 non-null  str
 11  amount                      126000 non-null  float64
 12  currency                    126000 non-null  str
 13  amount_to_avg_ratio         126000 non-null  float64
 14  avg_transaction_amount_30d  126000 non-null  float64
 15  transaction_velocity_1h     126000 non-null  int64
 16  transaction_country         126000 non-null  str
 17  home_country                126000 non-null  str
 18  is_cross_border             126000 non-null  int64
 19  device_id                   126000 non-null  str
 20  is_new_device               111666 non-null  float64
 21  account_age_days            126000 non-null  int64
 22  status                      126000 non-null  str
 23  is_fraud                    126000 non-null  int64
dtypes: datetime64[us](1), float64(4), int64(5), str(14)
memory usage: 23.1 MB

In [48]:
txn.duplicated().sum()

np.int64(0)

In [49]:
txn.info()

<class 'pandas.DataFrame'>
RangeIndex: 126000 entries, 0 to 125999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   transaction_id              126000 non-null  str
 1   account_id                  126000 non-null  str
 2   account_type                126000 non-null  str
 3   kyc_tier                    126000 non-null  str
 4   timestamp                   126000 non-null  datetime64[us]
 5   day_of_week                 126000 non-null  str
 6   hour_of_day                 126000 non-null  int64
 7   description                 126000 non-null  str
 8   merchant_name               97390 non-null   str
 9   merchant_category           126000 non-null  str
 10  channel                     126000 non-null  str
 11  amount                      126000 non-null  float64
 12  currency                    126000 non-null  str
 13  amount_to_avg_ratio         126000 non-null  float64
 14  avg_transaction_amount_30d  126000 non-null  float64
 15  transaction_velocity_1h     126000 non-null  int64
 16  transaction_country         126000 non-null  str
 17  home_country                126000 non-null  str
 18  is_cross_border             126000 non-null  int64
 19  device_id                   126000 non-null  str
 20  is_new_device               111666 non-null  float64
 21  account_age_days            126000 non-null  int64
 22  status                      126000 non-null  str
 23  is_fraud                    126000 non-null  int64
dtypes: datetime64[us](1), float64(4), int64(5), str(14)
memory usage: 23.1 MB

In [50]:
txn.isnull().sum()

transaction_id                    0
account_id                        0
account_type                      0
kyc_tier                          0
timestamp                         0
day_of_week                       0
hour_of_day                       0
description                       0
merchant_name                 28610
merchant_category                 0
channel                           0
amount                            0
currency                          0
amount_to_avg_ratio               0
avg_transaction_amount_30d        0
transaction_velocity_1h           0
transaction_country               0
home_country                      0
is_cross_border                   0
device_id                         0
is_new_device                 14334
account_age_days                  0
status                            0
is_fraud                          0
dtype: int64

In [51]:
txn.is_new_device.value_counts()

is_new_device
0.0    107771
1.0      3895
Name: count, dtype: int64

In [52]:
print(txn.columns.tolist())

['transaction_id', 'account_id', 'account_type', 'kyc_tier', 'timestamp', 'day_of_week', 'hour_of_day', 'description', 'merchant_name', 'merchant_category', 'channel', 'amount', 'currency', 'amount_to_avg_ratio', 'avg_transaction_amount_30d', 'transaction_velocity_1h', 'transaction_country', 'home_country', 'is_cross_border', 'device_id', 'is_new_device', 'account_age_days', 'status', 'is_fraud']

In [53]:
txn.duplicated().sum()

np.int64(0)

In [54]:
txn.info()

<class 'pandas.DataFrame'>
RangeIndex: 126000 entries, 0 to 125999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   transaction_id              126000 non-null  str
 1   account_id                  126000 non-null  str
 2   account_type                126000 non-null  str
 3   kyc_tier                    126000 non-null  str
 4   timestamp                   126000 non-null  datetime64[us]
 5   day_of_week                 126000 non-null  str
 6   hour_of_day                 126000 non-null  int64
 7   description                 126000 non-null  str
 8   merchant_name               97390 non-null   str
 9   merchant_category           126000 non-null  str
 10  channel                     126000 non-null  str
 11  amount                      126000 non-null  float64
 12  currency                    126000 non-null  str
 13  amount_to_avg_ratio         126000 non-null  float64
 14  avg_transaction_amount_30d  126000 non-null  float64
 15  transaction_velocity_1h     126000 non-null  int64
 16  transaction_country         126000 non-null  str
 17  home_country                126000 non-null  str
 18  is_cross_border             126000 non-null  int64
 19  device_id                   126000 non-null  str
 20  is_new_device               111666 non-null  float64
 21  account_age_days            126000 non-null  int64
 22  status                      126000 non-null  str
 23  is_fraud                    126000 non-null  int64
dtypes: datetime64[us](1), float64(4), int64(5), str(14)
memory usage: 23.1 MB

In [55]:
txn.isnull().sum()

transaction_id                    0
account_id                        0
account_type                      0
kyc_tier                          0
timestamp                         0
day_of_week                       0
hour_of_day                       0
description                       0
merchant_name                 28610
merchant_category                 0
channel                           0
amount                            0
currency                          0
amount_to_avg_ratio               0
avg_transaction_amount_30d        0
transaction_velocity_1h           0
transaction_country               0
home_country                      0
is_cross_border                   0
device_id                         0
is_new_device                 14334
account_age_days                  0
status                            0
is_fraud                          0
dtype: int64

In [56]:
txn['is_new_device'] = txn['is_new_device'].fillna('Unknown_device')

In [57]:
txn.isnull().sum()

transaction_id                    0
account_id                        0
account_type                      0
kyc_tier                          0
timestamp                         0
day_of_week                       0
hour_of_day                       0
description                       0
merchant_name                 28610
merchant_category                 0
channel                           0
amount                            0
currency                          0
amount_to_avg_ratio               0
avg_transaction_amount_30d        0
transaction_velocity_1h           0
transaction_country               0
home_country                      0
is_cross_border                   0
device_id                         0
is_new_device                     0
account_age_days                  0
status                            0
is_fraud                          0
dtype: int64

In [58]:
txn['merchant_name'] = txn['merchant_name'].fillna(txn['merchant_category'])

In [59]:
txn.head(30)

,transaction_id,account_id,account_type,kyc_tier,timestamp,day_of_week,hour_of_day,description,merchant_name,merchant_category,...,avg_transaction_amount_30d,transaction_velocity_1h,transaction_country,home_country,is_cross_border,device_id,is_new_device,account_age_days,status,is_fraud
0,FLR250216186265,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-02-16 14:55:35,Sunday,14,CNP PURCHASE - BOLT,Bolt,Travel,...,9143.33,0,NG,NG,0,Unknown_id,Unknown_device,903,Completed,0
1,FLR250423143305,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-23 13:35:40,Wednesday,13,WEB PURCHASE - SLACK,Slack,Subscription/SaaS,...,9143.33,0,NG,NG,0,Unknown_id,Unknown_device,969,Declined,0
2,FLR250424154897,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-24 12:30:34,Thursday,12,MOBILE PURCHASE - JUSTRITE SUPERSTORE,Justrite Superstore,Groceries,...,9143.33,0,NG,NG,0,DEV-9055235108,0.0,970,Completed,0
3,FLR250428101772,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-28 14:41:59,Monday,14,CNP PURCHASE - ADOBE CREATIVE CLOUD,Adobe Creative Cloud,Subscription/SaaS,...,14891.16,0,NG,NG,0,Unknown_id,Unknown_device,974,Completed,0
4,FLR250628102827,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-06-28 16:15:47,Saturday,16,MOBILE PURCHASE - APPLE STORE,Apple Store,Electronics,...,49609.59,0,NG,NG,0,DEV-9055235108,0.0,1035,Declined,0
5,FLR250826178973,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-08-26 12:48:44,Tuesday,12,ATM WITHDRAWAL - CHASE ATM,Chase ATM,ATM Withdrawal,...,49609.59,0,DE,NG,1,DEV-9055235108,0.0,1094,Completed,0
6,FLR250924142173,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-09-24 17:46:28,Wednesday,17,NIP TRANSFER TO PETER ADEKUNLE,P2P Transfer,P2P Transfer,...,49609.59,0,NG,NG,0,DEV-9055235108,0.0,1123,Completed,0
7,FLR250928113373,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-09-28 19:53:02,Sunday,19,MOBILE PURCHASE - NETFLIX,Netflix,Subscription/SaaS,...,206814.22,0,NG,NG,0,DEV-9055235108,0.0,1127,Completed,0
8,FLR251118136208,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-11-18 20:21:36,Tuesday,20,MOBILE PURCHASE - AMAZON,Amazon,Retail,...,31458.32,0,NG,NG,0,DEV-9055235108,0.0,1178,Completed,0
9,FLR251122148229,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-11-22 22:23:26,Saturday,22,WEB PURCHASE - SLACK,Slack,Subscription/SaaS,...,31458.32,0,NG,NG,0,DEV-9055235108,0.0,1182,Completed,0
10,FLR251218213918,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-12-18 20:50:17,Thursday,20,POS PURCHASE - BRITISH AIRWAYS,British Airways,Travel,...,6525.42,0,NG,NG,0,DEV-9055235108,0.0,1208,Completed,0
11,FLR260531222795,FLR-ACC-100000,Individual,Tier3_Enhanced,2026-05-31 16:13:54,Sunday,16,NIP TRANSFER TO DAVID ADEYEMI,P2P Transfer,P2P Transfer,...,14362.55,0,NG,NG,0,DEV-9055235108,0.0,1372,Declined,0
12,FLR260704180973,FLR-ACC-100000,Individual,Tier3_Enhanced,2026-07-04 10:12:33,Saturday,10,WEB PURCHASE - SPAR,Spar,Groceries,...,14362.55,0,NG,NG,0,DEV-9055235108,0.0,1406,Completed,0
13,FLR260724188954,FLR-ACC-100000,Individual,Tier3_Enhanced,2026-07-24 09:49:47,Friday,9,POS PURCHASE - GOTV,GOtv,Subscription/SaaS,...,14362.55,0,NG,NG,0,DEV-9055235108,0.0,1426,Completed,0
14,FLR251001102695,FLR-ACC-100001,Business,Tier1_Basic,2025-10-01 15:57:00,Wednesday,15,INTL WIRE - INTERNATIONAL WIRE REF957027,International Wire,Wire Transfer,...,7049844.86,0,NG,NG,0,DEV-6361365398,1.0,0,Completed,0
15,FLR251011114918,FLR-ACC-100001,Business,Tier1_Basic,2025-10-11 21:38:42,Saturday,21,MOBILE PURCHASE - SPOTIFY,Spotify,Subscription/SaaS,...,7049844.86,0,NG,NG,0,DEV-8800420964,0.0,0,Completed,0
16,FLR251028139294,FLR-ACC-100001,Business,Tier1_Basic,2025-10-28 14:38:27,Tuesday,14,SALARY - METRO CONSULTING,Payroll Transfer,Payroll Transfer,...,3559123.66,0,NG,NG,0,DEV-8800420964,0.0,0,Completed,0
17,FLR260429102156,FLR-ACC-100001,Business,Tier1_Basic,2026-04-29 18:05:45,Wednesday,18,INTL WIRE - INTERNATIONAL WIRE REF415926,International Wire,Wire Transfer,...,5304484.26,0,NG,NG,0,DEV-8800420964,0.0,2,Completed,0
18,FLR250220130662,FLR-ACC-100002,Business,Tier2_Verified,2025-02-20 07:09:36,Thursday,7,MOBILE PURCHASE - SHOPRITE,Shoprite,Groceries,...,3140.92,0,US,US,0,DEV-4177709201,0.0,0,Completed,0
19,FLR250809151743,FLR-ACC-100002,Business,Tier2_Verified,2025-08-09 01:32:52,Saturday,1,INTL WIRE - INTERNATIONAL WIRE REF760807,International Wire,Wire Transfer,...,3140.92,0,US,US,0,DEV-4177709201,0.0,0,Completed,0
20,FLR251109117671,FLR-ACC-100002,Business,Tier2_Verified,2025-11-09 18:05:22,Sunday,18,INTL WIRE - INTERNATIONAL WIRE REF447424,International Wire,Wire Transfer,...,3140.92,0,US,US,0,DEV-4177709201,0.0,0,Declined,0
21,FLR251208214741,FLR-ACC-100002,Business,Tier2_Verified,2025-12-08 08:56:49,Monday,8,NIP TRANSFER TO LAURA NWOSU,P2P Transfer,P2P Transfer,...,3140.92,0,US,US,0,DEV-4177709201,0.0,0,Completed,0
22,FLR260316225852,FLR-ACC-100002,Business,Tier2_Verified,2026-03-16 13:36:30,Monday,13,SALARY - NORTH VENTURES,Payroll Transfer,Payroll Transfer,...,3140.92,0,US,US,0,DEV-4177709201,0.0,0,Completed,0
23,FLR260619172291,FLR-ACC-100002,Business,Tier2_Verified,2026-06-19 07:39:03,Friday,7,API PURCHASE - EEDC,EEDC,Utilities,...,3140.92,0,US,US,0,DEV-4177709201,0.0,82,Completed,0
24,FLR260807109506,FLR-ACC-100002,Business,Tier2_Verified,2026-08-07 14:16:02,Friday,14,INTL WIRE - INTERNATIONAL WIRE REF284330,International Wire,Wire Transfer,...,3140.92,0,US,US,0,DEV-4177709201,0.0,131,Completed,0
25,FLR250318149063,FLR-ACC-100003,Individual,Tier3_Enhanced,2025-03-18 07:42:56,Tuesday,7,CNP PURCHASE - SAINSBURY'S,Sainsbury's,Groceries,...,10118.86,0,NG,NG,0,Unknown_id,Unknown_device,0,Completed,0
26,FLR250321187381,FLR-ACC-100003,Individual,Tier3_Enhanced,2025-03-21 09:48:10,Friday,9,NIP TRANSFER TO FUNKE FASHOLA,P2P Transfer,P2P Transfer,...,10118.86,0,NG,NG,0,Unknown_id,Unknown_device,0,Completed,1
27,FLR250416160374,FLR-ACC-100003,Individual,Tier3_Enhanced,2025-04-16 17:54:28,Wednesday,17,MOBILE PURCHASE - CVS PHARMACY,CVS Pharmacy,Healthcare,...,23919.66,0,NG,NG,0,Unknown_id,Unknown_device,0,Completed,0
28,FLR250812161590,FLR-ACC-100003,Individual,Tier3_Enhanced,2025-08-12 09:24:17,Tuesday,9,MOBILE PURCHASE - NOTION,Notion,Subscription/SaaS,...,1248.13,0,NG,NG,0,DEV-1814801537,0.0,0,Completed,0
29,FLR250813169435,FLR-ACC-100003,Individual,Tier3_Enhanced,2025-08-13 08:23:41,Wednesday,8,WEB PURCHASE - NOTION,Notion,Subscription/SaaS,...,1248.13,0,NG,NG,0,DEV-1814801537,0.0,0,Completed,0

In [60]:
acct.head(2)

,account_id,account_holder_name,account_type,home_country,currency,kyc_tier,account_created_date,personal_spend_baseline_usd
0,FLR-ACC-100000,Amaka Okafor,Individual,NG,NGN,Tier3_Enhanced,2022-08-28,63.23
1,FLR-ACC-100001,Bluewave Foods Ltd,Business,NG,NGN,Tier1_Basic,2026-04-27,810.68

In [61]:
txn.to_csv(r"C:\Users\Ifeoluwa\OneDrive\Documents\Finlora\data\processed\finlora_transactions_cleaned.csv", index=False)
acct.to_csv(r"C:\Users\Ifeoluwa\OneDrive\Documents\Finlora\data\processed\finlora_accounts_cleaned.csv", index=False)